# -*- coding: utf-8 -*-
"""autism_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OAm60W_uqsCTKKYFupy3UTJGYPgcp11-
"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Install required packages
!pip install mtcnn opencv-python dlib imutils scikit-learn xgboost matplotlib tqdm lz4 --quiet

# Download facial landmark predictor
!wget http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2
!bzip2 -d shape_predictor_68_face_landmarks.dat.bz2

import os
import numpy as np
import cv2
import dlib
import matplotlib.pyplot as plt
from imutils import face_utils
from mtcnn import MTCNN
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier
import joblib
from tqdm import tqdm

# Initialize MTCNN detector for initial face detection
mtcnn = MTCNN()

# Initialize dlib's face detector and landmark predictor for feature extraction
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor("shape_predictor_68_face_landmarks.dat")

def extract_features(landmarks):
    """
    Extract facial features from landmarks
    Returns a 9-dimensional feature vector
    """
    def euclidean(p1, p2):
        return np.linalg.norm(np.array(p1) - np.array(p2))

    # Extract the relevant facial landmarks
    left_eye = [landmarks[36], landmarks[39]]
    right_eye = [landmarks[42], landmarks[45]]
    nose = landmarks[30]
    mouth = [landmarks[48], landmarks[54]]
    jaw = [landmarks[4], landmarks[12]]

    # Calculate 6 distance features
    features = [
        euclidean(left_eye[0], left_eye[1]),    # Left eye width
        euclidean(right_eye[0], right_eye[1]),  # Right eye width
        euclidean(mouth[0], mouth[1]),          # Mouth width
        euclidean(nose, mouth[0]),              # Nose to left mouth corner
        euclidean(nose, mouth[1]),              # Nose to right mouth corner
        euclidean(jaw[0], jaw[1])               # Jaw width
    ]

    # Calculate 3 ratio features
    left_ear = euclidean(landmarks[37], landmarks[41]) / (features[0] + 1e-6)
    right_ear = euclidean(landmarks[43], landmarks[47]) / (features[1] + 1e-6)
    symmetry_ratio = features[0] / (features[1] + 1e-6)

    # Combine all features
    features.extend([left_ear, right_ear, symmetry_ratio])

    return np.array(features)

def load_and_extract_features(data_dir, categories=["Autistic", "Non_Autistic"]):
    """
    Load images from data_dir and extract facial features
    Returns feature matrix and labels
    """
    feature_matrix = []
    all_labels = []

    for label in categories:
        class_dir = os.path.join(data_dir, label)
        if not os.path.exists(class_dir):
            print(f"Warning: Directory {class_dir} does not exist")
            continue

        print(f"Processing {label} images...")
        for filename in tqdm(os.listdir(class_dir)):
            if not filename.lower().endswith((".jpg", ".png", ".jpeg")):
                continue

            img_path = os.path.join(class_dir, filename)
            try:
                # Read image
                img = cv2.imread(img_path)
                if img is None:
                    print(f"Failed to load image: {img_path}")
                    continue

                # Convert to RGB for MTCNN
                rgb_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

                # Detect face with MTCNN
                results = mtcnn.detect_faces(rgb_img)
                if not results:
                    # Try with dlib if MTCNN fails
                    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
                    faces = detector(gray)
                    if not faces:
                        print(f"No face detected in: {filename}")
                        continue

                    # Use the first face detected by dlib
                    face = faces[0]
                    shape = predictor(gray, face)
                    shape_np = face_utils.shape_to_np(shape)

                else:
                    # Use MTCNN result
                    face_box = results[0]['box']
                    x, y, w, h = face_box

                    # Ensure coordinates are valid
                    x, y = max(0, x), max(0, y)

                    # Convert to dlib rectangle
                    rect = dlib.rectangle(x, y, x + w, y + h)

                    # Get facial landmarks
                    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
                    shape = predictor(gray, rect)
                    shape_np = face_utils.shape_to_np(shape)

                # Extract features from landmarks
                features = extract_features(shape_np)

                # Add to dataset
                feature_matrix.append(features)
                all_labels.append(label)

            except Exception as e:
                print(f"Error processing {img_path}: {e}")

    return np.array(feature_matrix), np.array(all_labels)

# Define the training directory path - update this to your actual path
train_dir = '/content/drive/MyDrive/Kaggle-Autism-master/Kaggle-Autism-master/data/train'

# Extract features from training data
print("Extracting features from training data...")
feature_matrix, labels = load_and_extract_features(train_dir)

print(f"✅ Feature matrix shape: {feature_matrix.shape}")
print(f"✅ Total images processed: {len(labels)}")

# Encode labels
label_encoder = LabelEncoder()
labels_encoded = label_encoder.fit_transform(labels)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    feature_matrix, labels_encoded, test_size=0.2, random_state=42
)

# Train Random Forest model
print("Training Random Forest model...")
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Evaluate model
y_pred = rf_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"✅ Model trained. Accuracy: {accuracy:.4f}")

# Print classification report
print("\n📊 Classification Report:")
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

# Save the model
joblib.dump(rf_model, "autism_rf_classifier.pkl")
print("💾 Model saved as 'autism_rf_classifier.pkl'")

def predict_with_visuals(path, model=None, show_landmarks=True):
    """
    Predict autism from an image or directory of images with visualization

    Parameters:
    - path: Path to image file or directory
    - model: Pre-trained model (will load from file if None)
    - show_landmarks: Whether to show facial landmarks
    """
    # Load model if not provided
    if model is None:
        model = joblib.load("autism_rf_classifier.pkl")

    # Create label encoder with the same classes
    le = LabelEncoder()
    le.classes_ = np.array(["Autistic", "Non_Autistic"])

    def process_file(img_file):
        img = cv2.imread(img_file)
        if img is None:
            print(f"⚠️ Could not read '{img_file}'. Skipping.")
            return

        # Convert to RGB for display and grayscale for processing
        rgb_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        # Detect face with MTCNN
        results = mtcnn.detect_faces(rgb_img)

        if not results:
            # Try with dlib if MTCNN fails
            faces = detector(gray)
            if not faces:
                print(f"❌ No face detected in '{os.path.basename(img_file)}'.")
                plt.figure(figsize=(6,6))
                plt.imshow(rgb_img)
                plt.title(f"No face detected in {os.path.basename(img_file)}")
                plt.axis('off')
                plt.show()
                return

            face = faces[0]
            x, y, w, h = face.left(), face.top(), face.width(), face.height()

        else:
            # Use MTCNN result
            face_box = results[0]['box']
            x, y, w, h = face_box

        # Ensure coordinates are valid
        x, y = max(0, x), max(0, y)

        # Draw rectangle around face
        vis = rgb_img.copy()
        cv2.rectangle(vis, (x, y), (x + w, y + h), (0, 255, 0), 2)

        # Get facial landmarks
        rect = dlib.rectangle(x, y, x + w, y + h)
        shape = predictor(gray, rect)
        shape_np = face_utils.shape_to_np(shape)

        # Draw landmarks if requested
        if show_landmarks:
            for (x, y) in shape_np:
                cv2.circle(vis, (x, y), 2, (255, 0, 0), -1)

        # Extract features and predict
        feats = extract_features(shape_np).reshape(1, -1)
        pred_idx = model.predict(feats)[0]

        # Get prediction probabilities if available
        if hasattr(model, 'predict_proba'):
            probs = model.predict_proba(feats)[0]
            confidence = probs[pred_idx]
        else:
            confidence = None

        # Get label
        label = le.inverse_transform([pred_idx])[0]

        # Display result
        plt.figure(figsize=(8, 8))
        plt.imshow(vis)

        if confidence:
            plt.title(f"Prediction: {label} (Confidence: {confidence:.2f})", fontsize=14)
        else:
            plt.title(f"Prediction: {label}", fontsize=14)

        plt.axis('off')
        plt.show()

        # Print confidence for each class if available
        if hasattr(model, 'predict_proba'):
            print("Confidence by class:")
            for i, cls in enumerate(le.classes_):
                print(f"  {cls}: {probs[i]:.4f}")

        print("-" * 40)

    # Process single file or directory
    if os.path.isdir(path):
        for fname in sorted(os.listdir(path)):
            if fname.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp')):
                print(f"Processing {fname}...")
                process_file(os.path.join(path, fname))
    else:
        process_file(path)

# Load the trained model
model = joblib.load("autism_rf_classifier.pkl")

# Test on a sample image - update path to your test image
test_image = "/content/drive/MyDrive/Kaggle-Autism-master/Kaggle-Autism-master/data/test/Autistic/006.jpg"
print(f"Testing model on {test_image}")
predict_with_visuals(test_image, model)

# You can upload your own images to test
from google.colab import files
uploaded = files.upload()

for filename in uploaded.keys():
    print(f"Testing model on uploaded image: {filename}")
    predict_with_visuals(filename, model)

test_dir = "/content/drive/MyDrive/Kaggle-Autism-master/Kaggle-Autism-master/data/test"
print(f"Testing model on all images in {test_dir}")
predict_with_visuals(test_dir, model)

